<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h3><i class="fa fa-paypal"></i> <?php echo $this->translate('An error occurred in the process of payment!')?></h3>
            <hr/>
            <strong><?php echo $this->translate('Sorry, payment for the event selected has not been received!')?></strong><br/>
            <div style="margin-top:200px;">
                <a class="btn btn-success" href="/"><?php echo $this->translate('Homepage') ?></a>
                <a class="btn btn-default" href="/contact"><?php echo $this->translate('Contact') ?></a>
            </div>
        </div>
    </div>
</div>