<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h3><i class="fa fa-paypal"></i> <?php echo $this->translate('Your payment has been received!')?></h3>
            <hr/>
            <strong><?php echo $this->translate('Thank you for your purchase!')?></strong><br/>
            <?php echo $this->translate('You will receive an email from the Paypal service payment. Print it!')?>
            <div style="margin-top:200px;">
                <a class="btn btn-success" href="/"><?php echo $this->translate('Homepage') ?></a>
                <a class="btn btn-default" href="/contact"><?php echo $this->translate('Contact') ?></a>
            </div>
        </div>
    </div>
</div>